#if !canImport(ObjectiveC)
import XCTest

extension FiniteFieldTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FiniteFieldTests = [
        ("testAddition", testAddition),
        ("testAnd", testAnd),
        ("testComparison", testComparison),
        ("testDivision", testDivision),
        ("testEquality", testEquality),
        ("testExponentiation", testExponentiation),
        ("testHashing", testHashing),
        ("testInitBinaryInteger", testInitBinaryInteger),
        ("testInitBinaryIntegerClamping", testInitBinaryIntegerClamping),
        ("testInitBinaryIntegerExactly", testInitBinaryIntegerExactly),
        ("testInitBinaryIntegerTruncatingIfNeeded", testInitBinaryIntegerTruncatingIfNeeded),
        ("testInitFloatingPoint", testInitFloatingPoint),
        ("testInitFloatingPointExactly", testInitFloatingPointExactly),
        ("testInitIntegerLiteral", testInitIntegerLiteral),
        ("testInitString", testInitString),
        ("testLeftShift", testLeftShift),
        ("testMultiplication", testMultiplication),
        ("testNot", testNot),
        ("testOr", testOr),
        ("testRandom", testRandom),
        ("testRemainder", testRemainder),
        ("testRightShift", testRightShift),
        ("testStride", testStride),
        ("testSubtraction", testSubtraction),
        ("testXor", testXor),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FiniteFieldTests.__allTests__FiniteFieldTests),
    ]
}
#endif
